language: go
go: 1.13.x
install: go install
before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
script:
    - golangci-lint run  
    - go test -v -race ./...
